#!/usr/bin/env node
/**
 * Copies the compiled ABIs and the deployed addresses into the web app.
 *
 * Generated rather than pasted: an ABI typed by hand drifts from the contract the first time
 * a signature changes, and the drift shows up as an unexplained revert rather than a type
 * error. Run after every `forge build` that changes an interface.
 */
import {readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync} from "node:fs";
import {join} from "node:path";

const root = new URL("..", import.meta.url).pathname;
const outDir = join(root, "../web/lib/contracts");
mkdirSync(outDir, {recursive: true});

const HEADER = "// Generated by contracts/scripts-export-abi.mjs. Do not edit by hand.\n";

for (const name of ["PonsLock", "PonsAirdrop", "PonsDrip"]) {
  const artifact = JSON.parse(readFileSync(join(root, `out/${name}.sol/${name}.json`), "utf8"));
  const body =
    `${HEADER}\n/** ABI for ${name}, compiled from contracts/src/${name}.sol. */\n` +
    `export const ${name.charAt(0).toLowerCase()}${name.slice(1)}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  writeFileSync(join(outDir, `${name}.ts`), body);
  console.log(`${name}.ts  (${artifact.abi.length} entries)`);
}

// One address map per chain, keyed by chain id, so the app never holds a loose address.
const deployments = {};
const dir = join(root, "deployments");
if (existsSync(dir)) {
  for (const file of readdirSync(dir).filter((f) => f.endsWith(".json"))) {
    const d = JSON.parse(readFileSync(join(dir, file), "utf8"));
    deployments[d.chainId] = {
      PonsLock: d.PonsLock,
      PonsAirdrop: d.PonsAirdrop,
      // Absent on a deployment made before PonsDrip existed; the app checks before using it.
      PonsDrip: d.PonsDrip,
      deployedAtBlock: d.deployedAtBlock,
    };
  }
}

writeFileSync(
  join(outDir, "addresses.ts"),
  `${HEADER}
import type {SupportedChainId} from "@/lib/chain";

export interface Deployment {
  PonsLock: \`0x\${string}\`;
  PonsAirdrop: \`0x\${string}\`;
  /**
   * Optional because a chain deployed before PonsDrip existed has no entry for it. Anything
   * that needs drips has to check rather than assume, or it reads undefined as an address.
   */
  PonsDrip?: \`0x\${string}\`;
  /**
   * The L2 block the contracts went live at, for log scanning.
   *
   * Robinhood Chain is an Arbitrum Orbit chain, so \`block.number\` inside the EVM reports the
   * Ethereum L1 height. This is the real L2 height, read from the ArbSys precompile: starting
   * a scan from the other one would sweep about a hundred million empty blocks.
   */
  deployedAtBlock: number;
}

/** Written by the deploy script. A chain with no entry has no contracts yet. */
export const DEPLOYMENTS: Partial<Record<SupportedChainId, Deployment>> = ${JSON.stringify(deployments, null, 2)} as const;

export function deploymentFor(chainId: SupportedChainId): Deployment | undefined {
  return DEPLOYMENTS[chainId];
}
`,
);
console.log(`addresses.ts (chains: ${Object.keys(deployments).join(", ") || "none"})`);
