// Generated by contracts/scripts-export-abi.mjs. Do not edit by hand.

import type {SupportedChainId} from "@/lib/chain";

export interface Deployment {
  PonsLock: `0x${string}`;
  PonsAirdrop: `0x${string}`;
  /**
   * Optional because a chain deployed before PonsDrip existed has no entry for it. Anything
   * that needs drips has to check rather than assume, or it reads undefined as an address.
   */
  PonsDrip?: `0x${string}`;
  /**
   * The L2 block the contracts went live at, for log scanning.
   *
   * Robinhood Chain is an Arbitrum Orbit chain, so `block.number` inside the EVM reports the
   * Ethereum L1 height. This is the real L2 height, read from the ArbSys precompile: starting
   * a scan from the other one would sweep about a hundred million empty blocks.
   */
  deployedAtBlock: number;
}

/** Written by the deploy script. A chain with no entry has no contracts yet. */
export const DEPLOYMENTS: Partial<Record<SupportedChainId, Deployment>> = {
  "4663": {
    "PonsLock": "0x5386FEb416b7867f97c7ca3CA6B10c22d26F71D7",
    "PonsAirdrop": "0xAC2205d13316F5110C2bEE8Bb60c792608d46B2c",
    "PonsDrip": "0x74B04279dd9686FEF8E8F6a07A523bEab511504c",
    "deployedAtBlock": 64220583
  },
  "46630": {
    "PonsLock": "0x0B2B9B3D465c28F198729661A1B09F113D2CDd26",
    "PonsAirdrop": "0x74B04279dd9686FEF8E8F6a07A523bEab511504c",
    "PonsDrip": "0xd9Ed6570252fB1F5679F580248Db42D814ee73A0",
    "deployedAtBlock": 119908921
  }
} as const;

export function deploymentFor(chainId: SupportedChainId): Deployment | undefined {
  return DEPLOYMENTS[chainId];
}
